const productos = [
    {id:'1', title: 'Harry Potter', description:'El día de su cumpleaños, Harry Potter descubre que es hijo de dos conocidos hechiceros, de los que ha heredado poderes mágicos. Debe asistir a una famosa escuela de magia y hechicería, donde entabla una amistad con dos jóvenes que se convertirán en sus compañeros de aventura. Durante su primer año en Hogwarts, descubre que un malévolo y poderoso mago llamado Voldemort está en busca de una piedra filosofal que alarga la vida de quien la posee.', price:'$100', foto:'https://lh3.googleusercontent.com/d3AZMYAYoMMTMhUILK_g-My4_-su4kJoEu42oEVPz1FevurKKvk-EqgBnVzA1kED_KQhSRAm5uQokozRM7wcOVd5lIu0mfzuVIR24J5oy6nR4XGumfVRWvE67bXReymk7YfHzItyJfi8HPVHd273beDrV1agqoXmjZgZxwTJtyUiUHu2qot7fTSeNPDuIck3pD6fRA1P9mgW7bT0BC5e5btTVaJHDtPceGswr3mzbBMvr1oK0wt3LgB9UoL18jqQOTw99MjbKpGCNwb3cN23csOBrt8Mgbs-DoS0lJkyj-KumyAoXKIFHWXjy_POqyDBmyhndNDrIJ4l7ygWdQi8WGvQSJfMMczzslrmH4R80CP_FgduFySN0nBgNP4FLznH4TkLYnginDXG-_em_spHBe4HIIT3I1RtC7i8N8geItCsJuXeFQ3MkEAGa0UhzC6ACuGr06WSyE0MVRNqCcfDlsfdTrt2hxxgMUFhrZJeJUcUeJPi8dQ-hyEGW16uLc0eS7Mq9haUXEUKg4TX20wzp7gpSKh97CDtKi-Nc03S_qUOBH4lc5I6e6U8u-y5VbK4P9TcaW9v6QiiGg5H-XJM_q1OqcXP0RMrjlGwmytVAKQoRaFZlS1Uaj0XOnkjmMo5XiBRhLY2Qxn3wnFnN_AZktMrIA4QhZYCsKjRcb9Ta5306uhr5bwCimUmXHhkPTZFs5MWPjf6x_ClrPPFI-fvJ4xM=w413-h625-no?authuser=0'},
    {id:'2', title: 'El Principito', description:'El principito es una narración corta del escritor francés Antoine de Saint Exupéry, que trata de la historia de un pequeño príncipe que parte de su asteroide a una travesía por el universo, en la cual descubre la extraña forma en que los adultos ven la vida y comprende el valor del amor y la amistad.', price:'$100', foto:'https://lh3.googleusercontent.com/4i5U-ZSDukVrXmqITyBUSs3HhH9jWki9JTnSBjg6s6hgPpQRDBLTDYNHuU1gWMN7HRRF_u7e80hK7M2rK_hQBPXA_4HIUz1dw2IBs1IdCZ2nn_0BB4Dj_fB7lbq6UuxDCQxPKuKOaYM9xUL3TD_Eej_uK15Og5l23VRUbfmXRAcatN4m7HRDab2qUPxfTy7MUHvIZ7XvlP3arp_5mfYaKDmkWroc38m9tR-NF-7iaIs_HuobG9bQeth8zV7H0szNbnvIWty8Pv6doMWFbspToLhxor7H5hBRsL5MGWX5FKOFV4eBMZmY-hNiKfzCnETF96ep8t7h4rogFBNC7lODtaqYVq95HUgYHUrJTo1huaZ6DL50mViaPrvaJSVHrINolZQxuJrlG9cc9rzgVgSwEzaW9LkV6WbwCe9sQkaZ9zQC0wez1RC8FeWBJOJZqE3ovNOa4CoNAYR8dXpBoOdW7h7vIdsNcjUa8mKODBZs2sh29vyPuEaDl6g-xkoOrsbEBFi_gj17DSNOw0dx__ldisLT48WLEuNVix8YYqynn9LQTSgpXpG7N8LdhXdX0pGy3awtveWuTBOjZ0ZdmDcKQOdr7p9cFl6B_RvpuTZfYOqSJO5ayS6ar3RBCOjJ4N6Gir-PUBX6RXTwJ6qfUpOs9m5FQNh5IboWropCSwV2nlnZ1aKfhg3OIgLVN2n93yfOLZ6JWUtNa5wNCbMvoI82YiiO=w387-h625-no?authuser=0'},
    {id:'3', title: 'El Señor de los Anillos', description:'En la Tierra Media, el Señor Oscuro Sauron forjó los Grandes Anillos del Poder y creó uno con el poder de esclavizar a toda la Tierra Media. Frodo Bolsón es un hobbit al que su tío Bilbo hace portador del poderoso Anillo Único con la misión de destruirlo. Acompañado de sus amigos, Frodo emprende un viaje hacia Mordor, el único lugar donde el anillo puede ser destruido. Sin embargo, Sauron ordena la persecución del grupo para recuperar el anillo y acabar con la Tierra Media.', price:'$100', foto:'https://lh3.googleusercontent.com/9tpr5GsKyQJAn-mq8BqOdwn_er_tYti9hNBqqUt7x3hk8kta-RaavFZc7QJ0Dt_0CwVKdJY18FIQVs6_-6S4qqJJAvfNWNwL-og84Z35WwJ1hurcw5N251UPupZyRH0Y-4F7XUgm0uX30uRZO6GsUVzZMLGDGoNwD6deqXxhg0oA26sRtij-JfEr6YleyQYveATMTj6AexOxXsvaAHsleqlHzviNgR6sDKf5eM-5LZ_304DcGDMufOPabFOM8vM4G8IUe5iSxC_DQ55BoBlivbp2GmXqOpXGi_eNVHFJzpCmgrutBI-n3vcxzkOkTRvhkpqbaKHzcxChHm1Y8b8RHd0008h4r4m5U1epbaZZyH7JcvlRtuq3kVrzy0aWreyUjMYj1So4mprM8n3bKr7Y3rgg3E5Pw8ptptevfgZ6c9HZRDu-elwP3yfZtlbv2y99Eb-pOBRLYmdmJ3lCW0HTEVfE7ce3JQQF_h-DD0k8BiNBmSTRqqAfQeJwNS2U7gTdTbCV_Sd11JipV-iS-zAAC_wIzc5B3OY4GPsvWmWVsS7c1v5m0Eq8wlLqHLnWfZ4ck6Zh_uPE5_kNNtE1HevH2OFi0tB6fpADjc3tFp5LRAp4Ou4uDgpAWb8xRRfiJrIGbCE9y_H2SY5lnz3BYQs4t_4fa29PqIgHEPNMN6np_M8Dva9m0zbIdZXk2C0dAP56GA-Mg4HALb9jxk6WThpLOJY7=w220-h369-no?authuser=0'},
    {id:'4', title: 'Haikyuu', description:'La historia empieza cuando Shōyō Hinata, aún siendo un estudiante de primaria, ve un partido de voleibol por la televisión, en el cual ve jugar al conocido "Pequeño Gigante". Desde entonces, desea convertirse en alguien como él, debido a que ambos son bajos de estatura, y comienza a aficionarse por el deporte.', price:'$100', foto:'https://lh3.googleusercontent.com/hglPeXOdehmYLbF5fyR20yopu50jlhl3eCtR-EF85vDziQjcHmTBcuaZJTAzkW7I2KjG9igjy8c_kGutrvcKv42cZmWRu27You0V3vJ4phXchWexB9ZUUu2HXKn5pkWOIZp26F-oFPA04fMgfG4TathGqybpxQ8WkRBUMmieD2TlL0yYQT5XMHrIPmZyPtK4nBf5wZJc2kqnFJ7JpsRqNL2YxSvByewZF4wWUy6jjHvY5yYBUhXyEKx0KSkN_60DHsDYqZEgkRks9hFhcwRtxTf0QBiFjjKteEgc1dGooCH-CfaVh5J6RfeKVRSdEj4kxDf9uCb_p1JGctR95DbBCbunfkYuijQFL-oTrGOkPyzB2WhvgfK8tGEEYfI68892_H-OG_twvs2bAb6PlfR_BsB48x9WlXbWizKg3PMnSSVQNBvSKcyLcp58G8M-JFSxPKAP6PQ347QRJJ-7mk77OmLdhJiYMnO9V9g_boPDaQnshXAnuD6-RtPBjVyVGvUJU_HFYNHywo93o_8cFIX_QQXkaZek16-E7rBFejxfRD2PjM9ZDlx3wQYktOPJVwISbdp39IoMM4jsMZz7DY2FOytNq-1HDbDkUjHpDW5n3sGyAOpViaRfIPVmJI5hKCLwPoXGDn7icunLGKaOSe4uItbnGkWIiz_-LyBDd1xLOzqMOA6AGzZN_PZ-Cz1xCv5VNFq8H44p9Y15TYXES8H64jUn=w392-h625-no?authuser=0', autor: 'Haruichi Furudate', genero: 'Comics', idioma: 'Español'}
];

export const getFetch = new Promise ( (resolve, reject) => {
    let condicion = true;
    if (condicion){
        setTimeout(() => {
            resolve(productos)
        }, 2000)
    }else{
        reject('error')
    }    
})